# Generated by Django 3.2 on 2021-04-29 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_url', models.URLField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('register_date', models.DateField(default=datetime.datetime(2021, 4, 29, 19, 2, 48, 831968, tzinfo=utc))),
                ('description', models.TextField()),
                ('password_value', models.CharField(max_length=255)),
                ('extra_fields', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(null=True)),
                ('address_id', models.CharField(max_length=255)),
                ('formatted_address', models.CharField(max_length=255)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('ssn', models.CharField(max_length=9)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('license_plate', models.CharField(max_length=255)),
                ('vin', models.CharField(max_length=255)),
                ('retired', models.BooleanField(default=False)),
                ('purchase_year', models.DateField(null=True)),
                ('retire_date', models.DateField(null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringAccount',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='passman.account')),
                ('frequency', models.IntegerField(choices=[(0, 'Yearly'), (1, 'Monthly'), (2, 'Weekly'), (3, 'Daily')], default=1)),
                ('extra_params', models.JSONField(null=True)),
                ('acknowledge_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('issue_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('scan_image', stdimage.models.StdImageField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.TextField(null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_documents', to='passman.person')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('acknowledge_value', models.CharField(max_length=255, null=True)),
                ('comment', models.TextField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='passman.recurringaccount')),
            ],
        ),
    ]
