# Generated by Django 3.2 on 2021-05-03 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 3, 20, 54, 17, 534879, tzinfo=utc)),
        ),
    ]
