# Generated by Django 3.2 on 2021-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passman', '0002_auto_20210503_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apt_suite',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='register_date',
            field=models.DateField(default='django.utils.timezone.now'),
        ),
    ]
