# Generated by Django 3.2 on 2021-05-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passman', '0003_auto_20210504_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='comments',
            new_name='comment',
        ),
    ]
