# Generated by Django 3.2 on 2021-05-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passman', '0006_alter_address_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='register_date',
        ),
        migrations.AddField(
            model_name='account',
            name='username_value',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
