# Generated by Django 3.2 on 2021-05-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passman', '0007_auto_20210505_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='extra_fields',
        ),
        migrations.CreateModel(
            name='AccountExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('comment', models.TextField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='passman.account')),
            ],
        ),
    ]
