# Generated by Django 3.2 on 2021-05-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passman', '0008_auto_20210505_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_date']},
        ),
    ]
